version: "2.0"

services:
  worker:
    image: ghcr.io/drukpa1455/one-more-run-worker@sha256:df4bcb8cc4bf5bd2c99821287354c46335797e0bc07768bdbe7c984db18fa296
    expose:
      - port: 8080
        as: 80
        to:
          - global: true

profiles:
  compute:
    worker:
      resources:
        cpu:
          units: 4
        memory:
          size: 8Gi
        storage:
          - size: 16Gi
        gpu:
          units: 1
          attributes:
            vendor:
              nvidia:
                - model: rtx3090
                - model: rtx6000
                - model: v100
                - model: t4
  placement:
    akash:
      pricing:
        worker:
          denom: uact
          amount: 1000

deployment:
  worker:
    akash:
      profile: worker
      count: 1
